// Sapper's Path fix-v2 gen report: before/after numbers for the visual critic's MAJOR-1/2 (density, empty ground, the
// camp) and the functional critic's M1-M3 + m1/m2 (closest margin, the curve, one-card spam, stars, spare crews).
//   node tools/fixgen-report.js <before levels.json>    → tools/fix-v2-gen-report.md
// "Before" is the M1 v2 bake (commit 1ccf125), re-measured with today's solver so both sides use the same definitions.
"use strict";
const fs = require("fs"), path = require("path");
const E = require("../src/engine.js"), S = require("../src/solver.js");
const Art = require("./artmeta.js"), View = require("./artview.js"), Gen = require("./gen.js");
const C = JSON.parse(fs.readFileSync(path.join(__dirname, "bake-config.json"), "utf8")), DF = C.bake.difficulty;
const diffOf = (m) => DF.min * m.min + DF.decisions * m.decisions + DF.trap * m.trapRate + DF.rand * (1 - m.randWin);
const pct = (v) => Math.round(v * 100) + "%";
const med = (a) => { const b = a.slice().sort((x, y) => x - y); return b.length ? b[(b.length - 1) >> 1] : null; };
function hist(a) { const h = {}; for (const v of a) h[v] = (h[v] || 0) + 1; return Object.keys(h).sort((x, y) => (x === "none") - (y === "none") || x - y).map((k) => k + ":" + h[k]).join(" "); }

// Per level: the solver's view plus ground numbers and the camp's shape.
function rows(D) {
  const out = [];
  for (const w of D.worlds) for (const L of w.levels) {
    const B = E.parse(L), r = S.solve(B, { cap: C.cap }), p = { winRate: L.metrics.randWin }, gr = Art.ground(L);   // random win as the bake stored it
    let camp = 0, cy = new Set(), cx = new Set(); L.grid.forEach((row, y) => [...row].forEach((ch, x) => { if (ch === "P") { camp++; cy.add(y); cx.add(x); } }));
    let calls = 0; for (const k of E.CREWS) calls += L.muster[k] | 0;
    const m = { min: r.min, decisions: r.decisions, trapRate: r.trapRate, randWin: p.winRate };
    out.push({ id: L.id, world: w.world, teach: L.source === "teaching", min: r.min, dec: r.decisions, trap: r.trapRate, rand: p.winRate, diff: diffOf(m), margin: r.margin, slow: r.slowWin,
      spam: Gen.spamOf(B), mats: new Set(L.line).size, spare: calls + B.chestCell.length - r.min, gr, camp: cx.size + "x" + cy.size });
  }
  return out;
}
function world(R, k, baked) { return R.filter((r) => r.world === k && (!baked || !r.teach)); }

(() => {
  const beforeFile = process.argv[2];
  if (!beforeFile) { console.log("usage: node tools/fixgen-report.js <before levels.json>"); return; }
  const before = rows(JSON.parse(fs.readFileSync(beforeFile, "utf8"))), after = rows(JSON.parse(fs.readFileSync(path.join(__dirname, "..", "levels", "levels.json"), "utf8")));
  const md = [];
  md.push("# Sapper's Path: fix-v2 generator report", "",
    "Generated by `tools/fixgen-report.js`. *Before* is the M1 v2 bake (commit 1ccf125), *after* is this bake; both are re-measured with today's solver, so the definitions match. Seed " + C.seed + ", Rule A, no stacks.", "",
    "Definitions:",
    "- **Coverage**: crew-wall blocks (S T H I) over all board cells.",
    "- **Empty ground**: plain ground cells (`.`) with no decor on them, over all board cells. Before there was no decor, so it is all plain ground.",
    "- **Largest blank**: the side of the largest square of plain, undecorated ground.",
    "- **Closest margin**: along the optimal line, the smallest gap in walk (blocks) between a called crew's target and the next-nearest reachable wall of the same material. \"none\" = no call had a runner-up.",
    "- **Slower win**: a win in more than min calls exists (2 stars reachable).",
    "- **Spam**: calling one card again and again wins.",
    "- **Difficulty**: " + DF.min + "·min + " + DF.decisions + "·decision points + " + DF.trap + "·trap rate + " + DF.rand + "·(1 − random win).", "");

  md.push("## Density and empty ground (all levels, per world)", "", "| world | coverage before → after (median) | empty ground before → after (median, max) | largest blank before → after (median, max) | decor items (median) | camp shape after |", "|---|---|---|---|---|---|");
  for (let k = 1; k <= 4; k++) {
    const b = world(before, k), a = world(after, k);
    md.push("| " + k + " | " + pct(med(b.map((r) => r.gr.crew))) + " → " + pct(med(a.map((r) => r.gr.crew))) + " | " + pct(med(b.map((r) => r.gr.empty))) + ", " + pct(Math.max(...b.map((r) => r.gr.empty))) + " → " + pct(med(a.map((r) => r.gr.empty))) + ", " + pct(Math.max(...a.map((r) => r.gr.empty))) +
      " | " + med(b.map((r) => r.gr.bigBlank)) + ", " + Math.max(...b.map((r) => r.gr.bigBlank)) + " → " + med(a.map((r) => r.gr.bigBlank)) + ", " + Math.max(...a.map((r) => r.gr.bigBlank)) + " | " + med(a.map((r) => r.gr.decor)) + " | " + hist(a.map((r) => r.camp)) + " |");
  }
  md.push("", "Camp shape before: " + hist(before.map((r) => r.camp)) + " (width x depth).", "");

  md.push("## Depth, curve, spam and stars (baked levels, teaching boards excluded)", "", "| world | min calls before → after | decision points before → after | closest margin before → after | spam before → after | one-material lines before → after | slower win before → after | no spare before → after |", "|---|---|---|---|---|---|---|---|");
  for (let k = 1; k <= 4; k++) {
    const b = world(before, k, true), a = world(after, k, true);
    md.push("| " + k + " | " + b.map((r) => r.min).join(" ") + " → " + a.map((r) => r.min).join(" ") + " | " + b.map((r) => r.dec).join(" ") + " → " + a.map((r) => r.dec).join(" ") + " | " + hist(b.map((r) => (r.margin === null ? "none" : r.margin))) + " → " + hist(a.map((r) => (r.margin === null ? "none" : r.margin))) +
      " | " + b.filter((r) => r.spam).length + " → " + a.filter((r) => r.spam).length + " | " + b.filter((r) => r.mats < 2).length + " → " + a.filter((r) => r.mats < 2).length + " | " + b.filter((r) => r.slow).length + "/" + b.length + " → " + a.filter((r) => r.slow).length + "/" + a.length +
      " | " + b.filter((r) => r.spare <= 0).length + " → " + a.filter((r) => r.spare <= 0).length + " |");
  }
  const allB = before.filter((r) => !r.teach), allA = after.filter((r) => !r.teach);
  md.push("", "All 38 levels: slower win before " + before.filter((r) => r.slow).length + "/38, after " + after.filter((r) => r.slow).length + "/38 (the six teaching boards keep muster = min on purpose). Margin under 3 on a baked line: before " + allB.filter((r) => r.margin !== null && r.margin < 3).length + "/32, after " + allA.filter((r) => r.margin !== null && r.margin < 3).length + "/32.", "");

  md.push("## The curve (composite difficulty and random win, in play order)", "");
  for (const [name, R] of [["before", before], ["after", after]]) {
    md.push("**" + name + "**", "", "| world | difficulty (random win) per baked level | falls within the world | starts under the previous world's median |", "|---|---|---|---|");
    let floor = -1;
    for (let k = 1; k <= 4; k++) {
      const a = world(R, k, true), ds = a.map((r) => r.diff);
      let falls = 0; for (let i = 1; i < ds.length; i++) if (ds[i] < ds[i - 1] - 1e-9) falls++;
      const low = floor >= 0 ? a.filter((r) => r.diff < floor).length : 0;
      md.push("| " + k + " | " + a.map((r) => r.diff.toFixed(1) + " (" + r.rand.toFixed(2) + ")").join(" · ") + " | " + falls + " | " + (floor >= 0 ? low + " under " + floor.toFixed(1) : "-") + " |");
      floor = med(ds);
    }
    md.push("");
  }

  const ex = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "levels", "levels.json"), "utf8")).worlds[1].levels.find((l) => l.id === "w2-05");
  md.push("## Example with the `art` overlay: " + ex.id + " " + ex.name, "",
    "Left: the grid (`.` ground, `P` camp, `C` chest, `K` keep, S T H I F walls, `~` moat, `L` lever). Right: the same board with the art overlay drawn in: `#` tower rects, the gate rect in its side letter (`s` opens south, toward the camp), and decor as `b` bush, `f` flowers, `w` well, `c` cart, `r` barrel, `p` path. Muster " + JSON.stringify(ex.muster) + ", min " + ex.min + ", line " + ex.line.join(" "), "",
    "```", View.view(ex), "```", "",
    "`art` for this level: " + ex.art.towers.length + " towers " + JSON.stringify(ex.art.towers) + ", gates " + JSON.stringify(ex.art.gates) + ", keep " + JSON.stringify(ex.art.keep) + ", " + ex.art.decor.length + " decor items.", "");
  fs.writeFileSync(path.join(__dirname, "fix-v2-gen-report.md"), md.join("\n"));
  console.log("wrote tools/fix-v2-gen-report.md");
})();
