// Sapper's Path M0b distribution report: tools/bake-config.json → tools/m0b-report.md.
// Before/after with the same metrics: report.perWorld boards per world from the M0 generator (C.m0.worlds, the
// "before") and from castle() (C.worlds, the "after"), each measured BEFORE any accept filter, then each scored under
// its own bands (C.m0.bands via gen.accept, C.bands via gen.acceptB). Each column uses its band's spare.
// The narrative lives in tools/m0b-reading.md and is spliced in; bake.js keeps its own block at the end.
// Run: ~/.local/opt/node/bin/node tools/report.js
"use strict";
const fs = require("fs");
const path = require("path");
const Par = require("./par.js");
const Gen = require("./gen.js");
const E = require("../src/engine.js");

const q = (a, p) => { if (!a.length) return null; const b = a.slice().sort((x, y) => x - y); return b[Math.min(b.length - 1, Math.floor(p * b.length))]; };
const pct = (k, n) => (n ? Math.round((100 * k) / n) : 0) + "%";
const f2 = (v) => (v == null ? "n/a" : (+v).toFixed(2));
const trio = (a, fmt) => (a.length ? [0.1, 0.5, 0.9].map((p) => (fmt || String)(q(a, p))).join(" / ") : "n/a");
function hist(a) { const h = {}; for (const v of a) h[v] = (h[v] || 0) + 1; return Object.keys(h).sort((x, y) => x - y).map((k) => k + ":" + h[k]).join(" ") || "n/a"; }

// ASCII board with the optimal line numbered (1-9 then a-z) on each broken section's tiles.
function ascii(level, line) {
  const B = E.parse(level), mark = new Map(); line.forEach((s, i) => mark.set(s, i < 9 ? String(i + 1) : String.fromCharCode(88 + i)));
  return level.grid.map((row, y) => row + "    " + [...row].map((ch, x) => { const s = B.sec[y * B.w + x]; return s >= 0 && mark.has(s) ? mark.get(s) : ch; }).join("")).join("\n");
}
function lineText(level, line) { const B = E.parse(level); return line.map((s, i) => (i + 1) + ". " + E.crewOf(B, s) + " (" + E.sectionCells(B, s).length + " tiles)").join(", "); }

(async () => {
  const t0 = Date.now(), C = JSON.parse(fs.readFileSync(path.join(__dirname, "bake-config.json"), "utf8"));
  const tasks = [];
  for (const mode of ["m0", "castle"]) for (const wk of Object.keys(C.worlds)) for (let i = 0; i * C.chunk < C.report.perWorld; i++) tasks.push({ mode, wk, seed: C.seed + 7000000 + (+wk) * 100000 + i, n: C.chunk });
  const res = await Par.run(C, tasks);
  const by = {}, fails = {};
  tasks.forEach((t, i) => {
    const k = t.mode + t.wk; (by[k] = by[k] || []).push(...res[i].recs);
    for (const [r, v] of Object.entries(res[i].fails)) { fails[k] = fails[k] || {}; fails[k][r] = (fails[k][r] || 0) + v; }
  });
  const secs = ((Date.now() - t0) / 1000).toFixed(1);

  const out = [];
  out.push("# Sapper's Path: M0b distribution report", "");
  out.push("Generated by `tools/report.js` from `tools/bake-config.json` (seed " + C.seed + "). " + tasks.length + " worker tasks, " + secs + " s wall clock. For each world, " + C.report.perWorld + " boards from the M0 generator (**before**) and " + C.report.perWorld + " from the castle generator (**after**), all measured **before** any accept filter, then each scored under its own bands. Each column uses its band's muster spare (World 1: 0, Worlds 2-4: +1, the same in both).", "");
  out.push("**Metrics.** *Wall sections* counts every wall section, iron included (the decision's caps). *Stray singletons* are single-tile sections that are not a lever seal. *Random win* is the uniform-random playout win rate. *Trap rate* is the second proxy: across every reachable state from which a win is still reachable, the share of legal breaks that lose. *Decision points* are steps on the optimal line where at least one legal break loses. *Chest detour* = not required for 3 stars but claimable for at most one extra break. *Levers matter* = no win, or a higher min, with levers disabled.", "");
  out.push("{{READING}}", "");

  const summary = [];
  for (const wk of Object.keys(C.worlds)) {
    const W = C.worlds[wk], band = C.bands[wk], ob = C.m0.bands[wk];
    const before = by["m0" + wk] || [], after = by["castle" + wk] || [];
    const bAcc = before.filter((r) => !Gen.accept(r, ob)), aAcc = after.filter((r) => !Gen.acceptB(r, band));
    const cols = [[before, ob.spare], [bAcc, ob.spare], [after, band.spare], [aAcc, band.spare]].map(([R, sp]) => ({ R, M: R.map((r) => (sp ? r.s1 : r.s0)).filter((m) => m.win) }));
    out.push("## World " + wk + ": " + W.name, "");
    out.push("After: sizes " + W.sizes.join("/") + ", materials " + W.mats.join("") + ", plans " + Object.entries(W.plans).map(([s, p]) => s + "×" + s + " `" + p.join("`, `") + "`").join("; ") + ". Generator rejects before measuring: before " + JSON.stringify(fails["m0" + wk] || {}) + ", after " + JSON.stringify(fails["castle" + wk] || {}) + ".", "");
    out.push("| metric (p10 / p50 / p90 unless noted) | before, all | before, accepted | after, all | after, accepted |", "|---|---|---|---|---|");
    const row = (name, fn) => out.push("| " + name + " | " + cols.map((c) => (c.M.length ? fn(c.M, c.R) : "n/a")).join(" | ") + " |");
    row("boards", (M, R) => String(R.length));
    row("crew sections", (M) => trio(M.map((m) => m.sections)));
    row("wall sections (incl. iron)", (M) => trio(M.map((m) => m.sections + m.iron)));
    row("stray singletons (histogram)", (M) => hist(M.map((m) => (m.singles != null ? m.singles : 0))));
    row("min crews (histogram)", (M) => hist(M.map((m) => m.min)));
    row("random win", (M) => trio(M.map((m) => m.randWin), f2));
    row("trap rate", (M) => trio(M.map((m) => m.trapRate), f2));
    row("decision points (histogram)", (M) => hist(M.map((m) => m.decisions)));
    row("greedy fails", (M) => pct(M.filter((m) => !m.greedyWin).length, M.length));
    if (W.chests) {
      row("chest required for 3 stars", (M) => pct(M.filter((m) => m.chestRequired).length, M.length));
      row("chest detour", (M) => pct(M.filter((m) => m.chestKind === "detour").length, M.length));
    }
    if (W.lever) row("levers matter", (M) => pct(M.filter((m) => m.leversMatter).length, M.length));
    out.push("");
    // Stray singletons for the before column need the M0b measure; M0 boards are measured by the same measure(), so they are real.
    const why = {}; for (const r of after) { const k = Gen.acceptB(r, band); if (k) why[k] = (why[k] || 0) + 1; }
    const bwhy = {}; for (const r of before) { const k = Gen.accept(r, ob); if (k) bwhy[k] = (bwhy[k] || 0) + 1; }
    out.push("**Band (after):** spare " + (band.spare ? "+1" : "0") + ", min crews " + band.min.join("-") + ", at most " + band.maxSections + " wall sections and " + band.maxSingles + " stray singletons" + (band.greedy ? ", greedy fails or uses +2" : ", greedy rule off") + (band.decisions ? ", at least " + band.decisions + " decision point" + (band.decisions > 1 ? "s" : "") : "") + ", random win " + band.randWin.join("-") + ", trap rate " + band.trap.join("-") + (band.chest ? ", chest required or detour" : "") + (band.levers ? ", levers must matter" : "") + ".", "");
    out.push("**Accept rate:** before " + bAcc.length + " / " + before.length + " (" + pct(bAcc.length, before.length) + "). After " + aAcc.length + " / " + after.length + " (" + pct(aAcc.length, after.length) + "); rejections: " + Object.entries(why).sort((a, b) => b[1] - a[1]).map(([k, v]) => k + " " + v).join(", ") + ".", "");
    summary.push({ wk, before: before.length, bAcc: bAcc.length, after: after.length, aAcc: aAcc.length });
    // One example: the median accepted board by difficulty order.
    const ex = aAcc.slice().sort((a, b) => { const A = band.spare ? a.s1 : a.s0, B = band.spare ? b.s1 : b.s0; return A.min - B.min || B.randWin - A.randWin; })[Math.floor(aAcc.length / 2)];
    if (ex) {
      const m = band.spare ? ex.s1 : ex.s0, L = band.spare ? Gen.withSpare(ex.level, ex.info.spareCrew, 1) : ex.level;
      out.push("Example (median accepted board): " + L.w + "×" + L.h + ", plan `" + ex.info.plan + "`, muster " + JSON.stringify(L.muster) + (L.chests.length ? ", chest " + JSON.stringify(L.chests[0]) + " (" + m.chestKind + ")" : "") + ". Straight route with unlimited crews: " + ex.info.straight + ". Min " + m.min + ", random win " + f2(m.randWin) + ", trap rate " + f2(m.trapRate) + ", " + m.decisions + " decision points, greedy " + (m.greedyWin ? "wins with " + m.greedyUsed : "gets stuck after " + m.greedyUsed) + ", " + m.walls + " wall sections. Left: the board. Right: the optimal line, numbered in break order.", "");
      out.push("```", ascii(L, m.line), "```", "Line: " + lineText(L, m.line) + ".", "");
    }
  }
  out.push("## Summary", "", "| world | before: accepted | after: accepted | levels baked |", "|---|---|---|---|");
  for (const s of summary) out.push("| " + s.wk + " | " + s.bAcc + " / " + s.before + " (" + pct(s.bAcc, s.before) + ") | " + s.aAcc + " / " + s.after + " (" + pct(s.aAcc, s.after) + ") | " + C.bake.levels[s.wk] + " |");
  out.push("");
  let text = out.join("\n");
  const readingPath = path.join(__dirname, "m0b-reading.md");
  text = text.replace("{{READING}}", fs.existsSync(readingPath) ? fs.readFileSync(readingPath, "utf8").trim() : "_(reading not written yet)_");
  const rp = path.join(__dirname, "m0b-report.md"), prev = fs.existsSync(rp) ? fs.readFileSync(rp, "utf8") : "";
  const bake = prev.match(/<!-- bake:start -->[\s\S]*<!-- bake:end -->/);   // keep the last bake's block
  fs.writeFileSync(rp, text + (bake ? "\n" + bake[0] + "\n" : "\n"));
  console.log("report: " + Object.values(by).reduce((a, r) => a + r.length, 0) + " boards in " + secs + " s → tools/m0b-report.md");
  for (const s of summary) console.log("  W" + s.wk + " before " + s.bAcc + "/" + s.before + ", after " + s.aAcc + "/" + s.after);
})().catch((e) => { console.log("report failed: " + (e && e.stack || e)); });
