// Sapper's Path M0 v2 comparison report: tools/bake-config.json → tools/m0v2-report.md.
// For each world, report.perWorld castle pictures, each given its own scarce muster under Rule A and under Rule B
// (gen.musterize), plus Rule A + stacks (the A level's crews dealt into columns, gen.deal). Every metric of SPEC-v2 §5
// is measured BEFORE any accept filter; then each variant is scored under the same world bands (C.bands).
// The narrative lives in tools/m0v2-reading.md and is spliced in; bake.js keeps its own block at the end.
// Run: ~/.local/opt/node/bin/node tools/report.js
"use strict";
const fs = require("fs");
const path = require("path");
const Par = require("./par.js");
const Gen = require("./gen.js");
const E = require("../src/engine.js");

const q = (a, p) => { if (!a.length) return null; const b = a.slice().sort((x, y) => x - y); return b[Math.min(b.length - 1, Math.floor(p * b.length))]; };
const pct = (k, n) => (n ? Math.round((100 * k) / n) : 0) + "%";
const f2 = (v) => (v == null ? "n/a" : (+v).toFixed(2));
const f1 = (v) => (v == null ? "n/a" : (+v).toFixed(1));
const trio = (a, fmt) => (a.length ? [0.1, 0.5, 0.9].map((p) => (fmt || String)(q(a, p))).join(" / ") : "n/a");
const mean = (a) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : null);
function hist(a) { const h = {}; for (const v of a) h[v] = (h[v] || 0) + 1; return Object.keys(h).sort((x, y) => x - y).map((k) => k + ":" + h[k]).join(" ") || "n/a"; }
const VARIANTS = [["A", "Rule A"], ["B", "Rule B"], ["AS", "Rule A + stacks"]];

// ASCII board with the optimal line numbered (1-9 then a-z) on the tiles each call breaks.
function ascii(level, lineSecs) {
  const B = E.parse(level), mark = new Map();
  lineSecs.forEach((ss, i) => { for (const s of ss) mark.set(s, i < 9 ? String(i + 1) : String.fromCharCode(88 + i)); });
  return level.grid.map((row, y) => row + "    " + [...row].map((ch, x) => { const s = B.sec[y * B.w + x]; return s >= 0 && mark.has(s) ? mark.get(s) : ch; }).join("")).join("\n");
}
function lineText(level, m) {
  const B = E.parse(level);
  return m.line.map((a, i) => { const ss = m.lineSecs[i], mt = B.secMat[ss[0]]; return (i + 1) + ". " + E.CREWS[mt] + (B.cols ? " (column " + (a + 1) + ")" : "") + " → " + ss.map((s) => E.sectionCells(B, s).length).join("+") + " blocks"; }).join(", ");
}

(async () => {
  const t0 = Date.now(), C = JSON.parse(fs.readFileSync(path.join(__dirname, "bake-config.json"), "utf8"));
  const tasks = [];
  for (const wk of Object.keys(C.worlds)) for (let i = 0; i * C.chunk < C.report.perWorld; i++) tasks.push({ wk, seed: C.seed + 7000000 + (+wk) * 100000 + i, n: C.chunk, variants: ["A", "B", "AS"] });
  const res = await Par.run(C, tasks);
  const by = {}, fails = {};
  tasks.forEach((t, i) => {
    (by[t.wk] = by[t.wk] || []).push(...res[i].recs);
    for (const [r, v] of Object.entries(res[i].fails)) { fails[t.wk] = fails[t.wk] || {}; fails[t.wk][r] = (fails[t.wk][r] || 0) + v; }
  });
  const secs = ((Date.now() - t0) / 1000).toFixed(1), rec = C.rule + (C.stacksInBake ? "S" : "");

  const out = [], head = [];
  out.push("# Sapper's Path: M0 v2 comparison report", "");
  out.push("Generated by `tools/report.js` from `tools/bake-config.json` (seed " + C.seed + "). " + tasks.length + " worker tasks, " + secs + " s wall clock. For each world, " + C.report.perWorld + " castle pictures. Each picture gets its **own** scarce muster under Rule A and under Rule B (the same generator policy for both), and Rule A + stacks deals the Rule A level's crews into " + C.stacks.k + " columns. Every number below is measured **before** any accept filter; the accept rows then score all three variants under the same world bands.", "");
  out.push("**Metrics.** *Min calls* = the solver's minimum crews called. *Decision points* = steps on the optimal line where at least one legal call loses. *Trap rate* = across every state from which a win is still reachable, the share of legal calls that lose. *Random win* = uniform-random playouts (" + C.playouts + " per board). *Greedy* = always call the material whose target is nearest the keep; *excess* = its calls minus the minimum when it wins. *Tie rate* = boards where a tie-break decides some callable crew's target on a state along the optimal line (*on a move*: the tie decided the call the line makes). *Surprise rate* = boards where a wall the optimal line breaks later was reachable earlier but was not its crew's target (a closer wall of that material stood first: the player has to reshape \"closest\"); Rule B has none by definition. *A≠B* = the Rule A level solved under Rule B gives a different minimum. *Sections* = crew wall sections (iron not counted); *blocks* = mean blocks per crew section.", "");
  out.push("{{READING}}", "");

  const summary = [];
  for (const wk of Object.keys(C.worlds)) {
    const W = C.worlds[wk], band = C.bands[wk] || {}, R = by[wk] || [];
    const cols = VARIANTS.map(([k]) => { const recs = R.filter((r) => r.v[k] && r.v[k].m); return { k, recs, M: recs.map((r) => r.v[k].m).filter((m) => m.win) }; });
    out.push("## World " + wk + ": " + W.name, "");
    out.push("Sizes " + W.sizes.map((s) => s.join("×")).join(", ") + ", materials " + W.mats.join("") + ", depth search " + W.depth.join("-") + " calls with " + W.slack.join("-") + " slack. Castle rejects before measuring: " + JSON.stringify(fails[wk] || {}) + ". Variant failures: " + VARIANTS.map(([k]) => k + " " + R.filter((r) => !r.v[k] || !r.v[k].m).length).join(", ") + ".", "");
    out.push("| metric (p10 / p50 / p90 unless noted) | " + VARIANTS.map((v) => v[1]).join(" | ") + " |", "|---|---|---|---|");
    const row = (name, fn) => out.push("| " + name + " | " + cols.map((c) => (c.M.length ? fn(c.M, c) : "n/a")).join(" | ") + " |");
    row("boards measured", (M, c) => String(c.recs.length));
    row("min calls (histogram)", (M) => hist(M.map((m) => m.min)));
    row("min calls", (M) => trio(M.map((m) => m.min)));
    row("decision points (histogram)", (M) => hist(M.map((m) => m.decisions)));
    row("boards with ≥1 decision point", (M) => pct(M.filter((m) => m.decisions > 0).length, M.length));
    row("trap rate", (M) => trio(M.map((m) => m.trapRate), f2));
    row("random win", (M) => trio(M.map((m) => m.randWin), f2));
    row("greedy fails", (M) => pct(M.filter((m) => !m.greedyWin).length, M.length));
    row("greedy excess when it wins (mean)", (M) => f2(mean(M.filter((m) => m.greedyWin).map((m) => m.greedyExcess))));
    row("tie rate (any target / on a move)", (M) => pct(M.filter((m) => m.tieAny).length, M.length) + " / " + pct(M.filter((m) => m.tieMove).length, M.length));
    row("surprise rate (mean reshapes)", (M, c) => (c.k === "B" ? "0% (n/a)" : pct(M.filter((m) => m.reshapes > 0).length, M.length) + " (" + f1(mean(M.map((m) => m.reshapes))) + ")"));
    row("A≠B share", (M, c) => (c.k === "A" ? pct(M.filter((m) => m.minB !== m.min).length, M.length) + " (B lower on " + pct(M.filter((m) => m.minB != null && m.minB < m.min).length, M.length) + ")" : "-"));
    row("crew sections", (M) => trio(M.map((m) => m.sections)));
    row("blocks per section (mean)", (M) => trio(M.map((m) => m.blocks), f1));
    row("solve ms (p50 / p90)", (M) => q(M.map((m) => m.ms), 0.5) + " / " + q(M.map((m) => m.ms), 0.9));
    row("solver states (p50 / p90)", (M) => q(M.map((m) => m.states), 0.5) + " / " + q(M.map((m) => m.states), 0.9));
    row("capped", (M, c) => String(c.recs.filter((r) => r.v[c.k].m.capped).length));
    if (W.chests) row("chest required / detour", (M) => pct(M.filter((m) => m.chestKind === "required").length, M.length) + " / " + pct(M.filter((m) => m.chestKind === "detour").length, M.length));
    if (W.lever) row("levers matter", (M) => pct(M.filter((m) => m.leversMatter).length, M.length));
    row("accepted under the world band", (M, c) => { const a = c.recs.filter((r) => !Gen.accept(r.v[c.k].m, band)).length; return a + " / " + c.recs.length + " (" + pct(a, c.recs.length) + ")"; });
    out.push("");
    const acc = {};
    for (const c of cols) { const why = {}; for (const r of c.recs) { const k = Gen.accept(r.v[c.k].m, band); if (k) why[k] = (why[k] || 0) + 1; } acc[c.k] = { n: c.recs.filter((r) => !Gen.accept(r.v[c.k].m, band)).length, why }; }
    out.push("**Band:** min calls " + (band.min || []).join("-") + ", at most " + band.maxSections + " wall sections, no tie on a move, " + (band.greedy ? "greedy fails or uses +" + band.greedy : "greedy rule off") + ", at least " + band.decisions + " decision point" + (band.decisions === 1 ? "" : "s") + (band.reshapes ? ", at least " + band.reshapes + " reshape" : "") + ", random win " + (band.randWin || []).join("-") + ", trap rate " + (band.trap || []).join("-") + (band.chest ? ", chest required or detour" : "") + (band.levers ? ", levers must matter" : "") + ". Rejections: " + VARIANTS.map(([k]) => k + " {" + Object.entries(acc[k].why).sort((a, b) => b[1] - a[1]).map(([x, v]) => x + " " + v).join(", ") + "}").join("; ") + ".", "");
    const colA = cols[0], colB = cols[1], colS = cols[2];
    const med = (c, f) => (c.M.length ? q(c.M.map(f), 0.5) : null);
    summary.push({ wk, n: R.length, A: [med(colA, (m) => m.min), med(colA, (m) => m.trapRate)], B: [med(colB, (m) => m.min), med(colB, (m) => m.trapRate)], S: [med(colS, (m) => m.min), med(colS, (m) => m.trapRate)],
      dA: pct(colA.M.filter((m) => m.decisions > 0).length, colA.M.length), dB: pct(colB.M.filter((m) => m.decisions > 0).length, colB.M.length), dS: pct(colS.M.filter((m) => m.decisions > 0).length, colS.M.length),
      tie: pct(colA.M.filter((m) => m.tieAny).length, colA.M.length), tieMove: pct(colA.M.filter((m) => m.tieMove).length, colA.M.length), sur: pct(colA.M.filter((m) => m.reshapes > 0).length, colA.M.length),
      ab: pct(colA.M.filter((m) => m.minB !== m.min).length, colA.M.length), accA: acc.A.n, accB: acc.B.n, accS: acc.AS.n });
    // One example under the recommended variant: the median accepted board by difficulty.
    const rc = cols.find((c) => c.k === rec) || colA;
    const accepted = rc.recs.filter((r) => !Gen.accept(r.v[rc.k].m, band)).sort((a, b) => { const A = a.v[rc.k].m, B = b.v[rc.k].m; return A.min - B.min || B.randWin - A.randWin; });
    const ex = accepted[Math.floor(accepted.length / 2)];
    if (ex) {
      const v = ex.v[rc.k], m = v.m, L = v.level;
      out.push("Example under the recommended variant (" + rc.k + ", median accepted board): " + L.w + "×" + L.h + ", muster " + JSON.stringify(L.muster) + (L.stacks ? ", stacks " + JSON.stringify(L.stacks) : "") + (L.chests.length ? ", chest " + JSON.stringify(L.chests[0]) + " (" + m.chestKind + ")" : "") + ". Straight route with unlimited crews: " + v.info.straight + ". Min " + m.min + ", " + m.decisions + " decision points, trap rate " + f2(m.trapRate) + ", random win " + f2(m.randWin) + ", " + m.reshapes + " reshapes, greedy " + (m.greedyWin ? "wins with " + m.greedyUsed : "gets stuck after " + m.greedyUsed) + ", " + m.sections + " crew sections (" + f1(m.blocks) + " blocks each). Left: the board. Right: the optimal line, numbered in call order.", "");
      out.push("```", ascii(L, m.lineSecs), "```", "Line: " + lineText(L, m) + ".", "");
    }
  }
  out.push("## Summary", "", "Medians over all measured boards. *Decisions* = share of boards with at least one decision point.", "",
    "| world | boards | min A / B / A+S | trap rate A / B / A+S | decisions A / B / A+S | tie rate (on a move) | surprise | A≠B | accepted A / B / A+S |", "|---|---|---|---|---|---|---|---|---|");
  for (const s of summary) out.push("| " + s.wk + " | " + s.n + " | " + s.A[0] + " / " + s.B[0] + " / " + s.S[0] + " | " + f2(s.A[1]) + " / " + f2(s.B[1]) + " / " + f2(s.S[1]) + " | " + s.dA + " / " + s.dB + " / " + s.dS + " | " + s.tie + " (" + s.tieMove + ") | " + s.sur + " | " + s.ab + " | " + s.accA + " / " + s.accB + " / " + s.accS + " |");
  out.push("");
  let text = out.join("\n");
  const readingPath = path.join(__dirname, "m0v2-reading.md");
  text = text.replace("{{READING}}", fs.existsSync(readingPath) ? fs.readFileSync(readingPath, "utf8").trim() : "_(reading not written yet)_");
  const rp = path.join(__dirname, "m0v2-report.md"), prev = fs.existsSync(rp) ? fs.readFileSync(rp, "utf8") : "";
  const bake = prev.match(/<!-- bake:start -->[\s\S]*<!-- bake:end -->/);   // keep the last bake's block
  fs.writeFileSync(rp, text + (bake ? "\n" + bake[0] + "\n" : "\n"));
  console.log("report: " + Object.values(by).reduce((a, r) => a + r.length, 0) + " boards in " + secs + " s → tools/m0v2-report.md");
  for (const s of summary) console.log("  W" + s.wk + " n " + s.n + " min A/B/S " + s.A[0] + "/" + s.B[0] + "/" + s.S[0] + " trap " + f2(s.A[1]) + "/" + f2(s.B[1]) + "/" + f2(s.S[1]) + " dec " + s.dA + "/" + s.dB + "/" + s.dS + " tie " + s.tie + "(" + s.tieMove + ") sur " + s.sur + " AB " + s.ab + " acc " + s.accA + "/" + s.accB + "/" + s.accS);
})().catch((e) => { console.log("report failed: " + (e && e.stack || e)); });
