// Sapper's Path M0 distribution report: tools/bake-config.json → tools/m0-report.md.
// Generates report.perWorld boards per world BEFORE any accept filter, measures each at spare 0 and spare +1,
// then scores the proposedBands from the config (accept rates, recommended level counts, examples).
// Run: ~/.local/opt/node/bin/node tools/report.js
"use strict";
const fs = require("fs");
const path = require("path");
const Par = require("./par.js");
const Gen = require("./gen.js");
const E = require("../src/engine.js");

const q = (a, p) => { if (!a.length) return null; const b = a.slice().sort((x, y) => x - y); return b[Math.min(b.length - 1, Math.floor(p * b.length))]; };
const pct = (k, n) => (n ? Math.round((100 * k) / n) : 0) + "%";
const f2 = (v) => (v == null ? "n/a" : (+v).toFixed(2));
const trio = (a, fmt) => [0.1, 0.5, 0.9].map((p) => (fmt || String)(q(a, p))).join(" / ");
function hist(a) { const h = {}; for (const v of a) h[v] = (h[v] || 0) + 1; return Object.keys(h).sort((x, y) => x - y).map((k) => k + ":" + h[k]).join("  "); }

// ASCII board with the optimal line numbered (1-9 then a-z) on each broken section's tiles.
function ascii(level, line) {
  const B = E.parse(level), mark = new Map(); line.forEach((s, i) => mark.set(s, i < 9 ? String(i + 1) : String.fromCharCode(88 + i)));
  return level.grid.map((row, y) => row + "    " + [...row].map((ch, x) => { const s = B.sec[y * B.w + x]; return s >= 0 && mark.has(s) ? mark.get(s) : ch; }).join("")).join("\n");
}
function lineText(level, line) { const B = E.parse(level); return line.map((s, i) => (i + 1) + ". " + E.crewOf(B, s) + " (" + E.sectionCells(B, s).length + " tiles)").join(", "); }

(async () => {
  const t0 = Date.now(), C = JSON.parse(fs.readFileSync(path.join(__dirname, "bake-config.json"), "utf8"));
  const tasks = [];
  for (const wk of Object.keys(C.worlds)) for (let i = 0; i * C.chunk < C.report.perWorld; i++) tasks.push({ wk, seed: C.seed + 7000000 + (+wk) * 100000 + i, n: C.chunk });
  const res = await Par.run(C, tasks);
  const by = {}, fails = {};
  tasks.forEach((t, i) => { (by[t.wk] = by[t.wk] || []).push(...res[i].recs); for (const [k, v] of Object.entries(res[i].fails)) { fails[t.wk] = fails[t.wk] || {}; fails[t.wk][k] = (fails[t.wk][k] || 0) + v; } });
  const secs = ((Date.now() - t0) / 1000).toFixed(1);

  const out = [];
  out.push("# Sapper's Path: M0 distribution report", "");
  out.push("Generated by `tools/report.js` from `tools/bake-config.json` (seed " + C.seed + "). " + tasks.length + " worker tasks, " + secs + " s wall clock. Every board below is measured **before** any accept filter. Each board is measured twice: with the muster exactly equal to the optimal line's crews (spare 0) and with one extra crew of a random material on the board (spare +1).", "");
  out.push("**Random-playout win rate is a proxy.** It is a uniform-random player picking any legal break. A human reads the board and does far better, so the absolute numbers look harsh; what the proxy is good for is *ordering* boards and separating worlds. The Food Hunt calibration below is a judgment on that ordering, not a measured human solve rate. M2's playtest (Peter, then Henry cold) is the real check.", "");
  out.push("{{READING}}", "");

  const summary = {};
  for (const wk of Object.keys(C.worlds)) {
    const W = C.worlds[wk], R = by[wk] || [], band = C.proposedBands[wk];
    out.push("## World " + wk + ": " + W.name, "");
    out.push("Sizes " + W.sizes.join("/") + ", materials " + W.mats.join("") + ", bands `" + W.bands + "`" + (W.chests ? ", 1 chest" : "") + (W.moat ? ", moat" : "") + (W.doors ? ", iron doors " + W.doors.join("–") + " + levers" : "") + ". Boards generated: " + R.length + ". Generator rejects before measuring: " + (JSON.stringify(fails[wk] || {}) === "{}" ? "none" : JSON.stringify(fails[wk])) + ".", "");
    out.push("| metric (p10 / p50 / p90 unless noted) | spare 0 | spare +1 |", "|---|---|---|");
    const col = (fn) => ["s0", "s1"].map((s) => fn(R.map((r) => r[s]).filter((m) => m.win)));
    const row = (name, fn) => out.push("| " + name + " | " + col(fn).join(" | ") + " |");
    row("crew sections on the board", (M) => trio(M.map((m) => m.sections)));
    row("min crews (histogram)", (M) => hist(M.map((m) => m.min)));
    row("random-playout win rate", (M) => trio(M.map((m) => m.randWin), f2));
    row("greedy fails", (M) => pct(M.filter((m) => !m.greedyWin).length, M.length));
    row("greedy excess when it wins (histogram)", (M) => hist(M.filter((m) => m.greedyWin).map((m) => m.greedyExcess)) || "n/a");
    row("order matters (greedy fails or +2)", (M) => pct(M.filter((m) => m.orderMatters).length, M.length));
    row("reachable states", (M) => trio(M.map((m) => m.states)));
    row("dead-end ratio (stuck / states)", (M) => trio(M.map((m) => m.deadRatio), f2));
    row("lost ratio (no win from here / states)", (M) => trio(M.map((m) => m.lostRatio), f2));
    row("solve ms p50 / p95", (M) => q(M.map((m) => m.ms), 0.5) + " / " + q(M.map((m) => m.ms), 0.95));
    row("capped", (M) => String(R.length - M.length ? R.filter((r) => r.s0.capped).length : M.filter((m) => m.capped).length));
    if (W.chests) {
      row("chest placed", () => pct(R.filter((r) => r.level.chests.length).length, R.length));
      row("chest on an optimal line", (M) => pct(M.filter((m) => m.chestOnOptimal).length, M.length));
      row("chest required for 3 stars", (M) => pct(M.filter((m) => m.chestRequired).length, M.length));
    }
    if (W.doors) {
      row("levers placed (histogram)", (M) => hist(M.map((m) => m.levers)));
      row("levers matter (min rises or no win without them)", (M) => pct(M.filter((m) => m.leversMatter).length, M.length));
      row("cascade placed (lever beside the previous door)", () => pct(R.filter((r) => r.info.cascade).length, R.length));
    }
    out.push("");

    // Proposed band + accept rate + examples.
    const acc = R.filter((r) => !Gen.accept(r, band)), why = {};
    for (const r of R) { const k = Gen.accept(r, band); if (k) why[k] = (why[k] || 0) + 1; }
    const want = C.bake.levels[wk];
    summary[wk] = { n: R.length, acc: acc.length, rate: R.length ? acc.length / R.length : 0, band, want };
    out.push("**Proposed band:** spare " + (band.spare ? "+1" : "0") + ", random win " + band.randWin.join("–") + ", min crews " + band.min.join("–") + ", at most " + band.maxSections + " crew sections" + (band.chest ? ", chest on an optimal line" : "") + (band.levers ? ", levers must matter" : "") + ". Plus the SPEC rules: a win exists, greedy fails or uses +2.", "");
    out.push("**Accept rate:** " + acc.length + " / " + R.length + " (" + pct(acc.length, R.length) + "). Rejections: " + Object.entries(why).sort((a, b) => b[1] - a[1]).map(([k, v]) => k + " " + v).join(", ") + ".", "");
    const rw = acc.map((r) => (band.spare ? r.s1 : r.s0).randWin), mn = acc.map((r) => (band.spare ? r.s1 : r.s0).min);
    if (acc.length) out.push("Accepted boards: random win " + trio(rw, f2) + ", min crews " + hist(mn) + ", sections " + trio(acc.map((r) => r.s0.sections)) + ".", "");
    const ex = acc.slice().sort((a, b) => (band.spare ? b.s1 : b.s0).randWin - (band.spare ? a.s1 : a.s0).randWin);
    const picks = ex.length ? [ex[Math.floor(ex.length * 0.25)], ex[Math.floor(ex.length * 0.8)]].slice(0, C.report.examples) : [];
    picks.forEach((r, i) => {
      const m = band.spare ? r.s1 : r.s0, L = band.spare ? Gen.withSpare(r.level, r.info.spareCrew, 1) : r.level;
      out.push("Example " + (i + 1) + " (" + (i ? "harder" : "easier") + " end of the accepted pool): " + L.w + "×" + L.h + ", muster " + JSON.stringify(L.muster) + (L.chests.length ? ", chest " + JSON.stringify(L.chests[0]) : "") + ". Min " + m.min + ", random win " + f2(m.randWin) + ", greedy " + (m.greedyWin ? "wins with " + m.greedyUsed : "gets stuck after " + m.greedyUsed) + ", " + m.sections + " sections. Left: the board. Right: the optimal line, numbered in break order.", "");
      out.push("```", ascii(L, m.line), "```", "Line: " + lineText(L, m.line) + ".", "");
    });
  }

  out.push("## Summary under the proposed bands", "", "| world | boards | accepted | accept rate | levels in the draft bake |", "|---|---|---|---|---|");
  for (const [wk, s] of Object.entries(summary)) out.push("| " + wk + " | " + s.n + " | " + s.acc + " | " + pct(s.acc, s.n) + " | " + s.want + (wk === "1" ? " (3 teaching + " + (s.want - 3) + " baked)" : "") + " |");
  out.push("");
  let text = out.join("\n");
  const readingPath = path.join(__dirname, "m0-reading.md");
  text = text.replace("{{READING}}", fs.existsSync(readingPath) ? fs.readFileSync(readingPath, "utf8").trim() : "_(reading not written yet)_");
  const rp = path.join(__dirname, "m0-report.md"), prev = fs.existsSync(rp) ? fs.readFileSync(rp, "utf8") : "";
  const bake = prev.match(/<!-- bake:start -->[\s\S]*<!-- bake:end -->/);   // keep the last bake's block
  fs.writeFileSync(rp, text + (bake ? "\n" + bake[0] + "\n" : "\n"));
  console.log("report: " + Object.values(by).reduce((a, r) => a + r.length, 0) + " boards in " + secs + " s → tools/m0-report.md");
  for (const [wk, s] of Object.entries(summary)) console.log("  W" + wk + " accept " + s.acc + "/" + s.n);
})().catch((e) => { console.log("report failed: " + (e && e.stack || e)); });
